POST http://127.0.0.1:8000/account/
Content-Type: application/json

{
  "username": "customer_one",
  "email": "customer@example.com",
  "password": "securepassword123",
  "user_type": "customer",
  "phone": "0123456789",
  "birth_date": "1990-05-20"
}

POST http://127.0.0.1:8000/account/
Content-Type: application/json

{
  "username": "issif",
  "email": "issifm@business.com",
  "password": "supersecurepassword",
  "user_type": "firm",
  "company_name": "issif Tech Solutions Inc.",
  "company_category": "Commerce",
  "siret": "12347678901284",
  "address": "123 Tech Park, Innovation City"
}

POST http://127.0.0.1:8000/account/login/
Content-Type: application/json

{
  "email": "customer@example.com",
  "password": "securepassword123"
}