### Create OWNER Account
POST http://127.0.0.1:8000/account/
Content-Type: application/json

{
  "username": "owner",
  "email": "sinistre12@gmail.com",
  "password": "securepassword123",
  "user_type": "customer",
  "phone": "0123456789",
  "birth_date": "1990-05-20"
}

### Create KARA Account
POST http://127.0.0.1:8000/account/
Content-Type: application/json

{
  "username": "KARA_225",
  "email": "Attaangek@gmail.com",
  "password": "Romaric1",
  "user_type": "customer",
  "phone": "0145896230",
  "birth_date": "2000-05-20"
}

### Create issif Account
POST http://127.0.0.1:8000/account/
Content-Type: application/json

{
  "username": "issif",
  "email": "issifm@business.com",
  "password": "supersecurepassword",
  "user_type": "firm",
  "company_name": "issif Tech Solutions Inc.",
  "address": "123 Tech Park, Innovation City",
  "phone_number": "0145896230"
}

### Create cainvest Account
POST http://127.0.0.1:8000/account/
Content-Type: application/json

{
  "username": "cainvest",
  "email": "cainvest@gmail.com",
  "password": "supersecurepassword",
  "user_type": "firm",
  "company_name": "Caladrius Inc.",
  "address": "225 Cocody, Innovation City",
  "phone_number": "0102030405"
}

### Create Ismo Account
POST http://127.0.0.1:8000/account/
Content-Type: application/json

{
  "username": "Ismo shop",
  "email": "Caladrius25@gmail.com",
  "password": "supersecurepassword",
  "user_type": "firm",
  "company_name": "Ismo shop",
  "company_category": "industrie",
  "siret": "12347678932589",
  "address": "225 Cocody, Innovation City",
  "phone_number": "0102030405"
}

### Create Ismo Account
POST http://127.0.0.1:8000/account/password-reseting/
Content-Type: application/json

{
  "email": "sinistre12@gmail.com"
}

POST http://127.0.0.1:8000/account/password-reset/confirm/
Content-Type: application/json

{
  "token": "ad83f842-1c56-4497-8f83-abec2a37f875",
  "new_password": "NouveauMotDePasseSecure123!"
}

POST http://127.0.0.1:8000/account/password-reset/verify-token/
Content-Type: application/json

{
  "token": "be7ee026-47d6-4f1b-8f5f-9e08db0d02e1"
}

POST http://127.0.0.1:8000/account/login/
Content-Type: application/json

{
  "email": "abdoulaziz@gmail.com",
  "password": "Jeanyves123456@"
}

POST http://127.0.0.1:8000/account/logout/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzUzOTcyMzAxLCJpYXQiOjE3NTM5Njg3MDEsImp0aSI6IjYzNjMzNDA5ODk3MzQxNDQ4MzMyZjdmM2ViNTZlYjJmIiwidXNlcl9pZCI6Nn0.7omf7VidykqPI1S_pL7pDSwjVYu3KWnl9Xak05VCzlA

{
  "refresh": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoicmVmcmVzaCIsImV4cCI6MTc1NDA1NTEwMSwiaWF0IjoxNzUzOTY4NzAxLCJqdGkiOiJiODBiY2RkYjk2NTI0ZDg1OTVhOTRmZDY3OGVhMmUwYyIsInVzZXJfaWQiOjZ9.TCzlFTBPuauP86fB2m0GxeoJEx2ugDaN7naUXQSXVjo"
}

PUT http://127.0.1:8000/account/profile/
Content-Type: application/json

{
  "email": "abdoulaziz@gmail.com",
  "first_name": "Abdoul",
  "last_name": "Aziz",
  "phone_number": "0123456789",
  "company_logo": "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAUA..."
}