# Generated by Django 5.2.4 on 2025-08-21 23:24

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0006_remove_firmprofile_siret_firmprofile_phone_number'),
        ('reviews', '0004_alter_review_options_alter_reviewresponse_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notifications',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notifications_type', models.CharField(choices=[('review_posted', 'Avis posté'), ('review_approved', 'Avis approuvé'), ('review_rejected', 'Avis rejeté'), ('review_responded', 'Avis repondu'), ('company_claimed', 'Entreprise réclamée')], max_length=50)),
                ('message', models.TextField()),
                ('data', models.JSONField(blank=True, default=dict)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('target_url', models.URLField(blank=True, null=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='account.customerprofile')),
                ('firm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifcations', to='account.firmprofile')),
                ('review', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifcations', to='reviews.review')),
                ('review_response', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifcations', to='reviews.reviewresponse')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
