# Generated by Django 5.1.7 on 2025-08-22 00:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_remove_firmprofile_siret_firmprofile_phone_number'),
        ('core', '0001_initial'),
        ('reviews', '0004_alter_review_options_alter_reviewresponse_options_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Notifications',
            new_name='Notification',
        ),
    ]
