# Generated by Django 5.1.7 on 2025-08-22 00:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_rename_notifications_notification'),
        ('reviews', '0004_alter_review_options_alter_reviewresponse_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='review_response',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifcations', to='reviews.reviewresponse'),
        ),
    ]
