# Generated by Django 5.1.7 on 2025-08-22 00:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_notification_review_response'),
        ('reviews', '0004_alter_review_options_alter_reviewresponse_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='review_response',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='reviews.reviewresponse'),
        ),
    ]
