POST http://127.0.0.1:8000/account/login/
Content-Type: application/json

{
  "email": "sinistre12@gmail.com",
  "password": "securepassword123"
}

POST http://127.0.0.1:8000/account/login/
Content-Type: application/json

{
  "email": "abdoulaziz@gmail.com",
  "password": "Jeanyves123456@"
}

POST http://127.0.0.1:8000/reviews/firms/4/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzUzNjMzNjQwLCJpYXQiOjE3NTM2MzAwNDAsImp0aSI6IjdiM2MxNDU1Y2ZiNDRhZWE5YzAyOGQ5ZmM4MDBhZGU1IiwidXNlcl9pZCI6IjIifQ.qGeCTC6PHD6NZ2y2SbqQ51cWBIr4YiMUBjs-_GyYuxA"


{
  "rating": 4,
  "comment": "Service Exelent, je recommande ils ont fait mon site en moins d'une semaine"
}

GET http://127.0.0.1:8000/reviews/public/recent/
Content-Type: application/json

POST http://127.0.0.1:8000/reviews/2/respond/
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzUzNTM2OTAyLCJpYXQiOjE3NTM1MzMzMDIsImp0aSI6IjAxOWM4MzU1NTMyNzQ2OTdhOGZiZmE2NzYyYTllNWY4IiwidXNlcl9pZCI6IjIifQ.Salp6_Fc1yEZd9LXajM-5wUd_k9VG96n9v5SSiVUFOg
Content-Type: application/json

{
  "response_text": "Merci pour votre retour, nous allons améliorer notre service."
}
