POST http://127.0.0.1:8000/account/login/
Content-Type: application/json

{
  "email": "sinistre12@gmail.com",
  "password": "securepassword123"
}

###
POST http://127.0.0.1:8000/account/
Content-Type: application/json

{
  "username": "owner",
  "email": "sinistre12@gmail.com",
  "password": "securepassword123",
  "user_type": "customer",
  "phone": "0123456789",
  "birth_date": "1990-05-20"
}

###
POST http://127.0.0.1:8000/account/login/
Content-Type: application/json

{
  "email": "jean.dupont@email.com",
  "password": "securepassword123"
}

###
POST http://127.0.0.1:8000/reviews/firms/3/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzU1OTU5MzMyLCJpYXQiOjE3NTU5NTIxMzIsImp0aSI6ImQ0YThiNDMwMzg3ZTRjYTFiYTdjMzg0MjhkOTllYWU2IiwidXNlcl9pZCI6N30.FJ1HV-bl_XadgVBWx-pXdww089JpX5mxV7d4t653UT4

{
  "rating": 4,
  "comment": "On vient tester le système de notifications"
}

###
{
  "refresh": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoicmVmcmVzaCIsImV4cCI6MTc1NjEyNDkzMiwiaWF0IjoxNzU1OTUyMTMyLCJqdGkiOiI1Nzc1OGEwNzg0NDU0YWVjYmZiYTQ4ZmI0MjFlOGJjMSIsInVzZXJfaWQiOjd9.fYBYXY1r2Nadvg_zZ49fJ6xH_XZq8zt1sC-6qV1nUyI",
  "access": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzU1OTU5MzMyLCJpYXQiOjE3NTU5NTIxMzIsImp0aSI6ImQ0YThiNDMwMzg3ZTRjYTFiYTdjMzg0MjhkOTllYWU2IiwidXNlcl9pZCI6N30.FJ1HV-bl_XadgVBWx-pXdww089JpX5mxV7d4t653UT4",
  "username": "jean.dupont"
}
###
{
  "refresh": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoicmVmcmVzaCIsImV4cCI6MTc1NTg5NjQwMiwiaWF0IjoxNzU1NzIzNjAyLCJqdGkiOiIxNGM1OGI5YjY5ZDI0ZGZmYjc0MmI4M2ZhMmI0ZjlmOSIsInVzZXJfaWQiOiIzIn0.dWimP8YBW_rzkTTJi703DCRl7NSGJebwDTiL9qop5OQ",
  "access": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzU1NzMwODAyLCJpYXQiOjE3NTU3MjM2MDIsImp0aSI6IjExNzljNTFlN2Y5MzQ4YTM5ZmJkOGUzOWUwNmQzMGI0IiwidXNlcl9pZCI6IjMifQ.nsosMIRFMlPEcDt34CeNYcIHF8fds8UFc6-h2sIu6Gg",
  "username": "KARA_225"
}

GET http://127.0.0.1:8000/reviews/public/recent/
Content-Type: application/json

### Get a specific reviews
GET http://127.0.0.1:8000/reviews/5/
Content-Type: application/json

### Get specific reviews about that firm
GET http://127.0.0.1:8000/reviews/firm/2/review/
Content-Type: application/json

POST http://127.0.0.1:8000/reviews/2/respond/
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzUzNTM2OTAyLCJpYXQiOjE3NTM1MzMzMDIsImp0aSI6IjAxOWM4MzU1NTMyNzQ2OTdhOGZiZmE2NzYyYTllNWY4IiwidXNlcl9pZCI6IjIifQ.Salp6_Fc1yEZd9LXajM-5wUd_k9VG96n9v5SSiVUFOg
Content-Type: application/json

{
  "response_text": "Merci pour votre retour, nous allons améliorer notre service."
}
