# Generated by Django 5.1.7 on 2025-07-24 17:25

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0005_passwordresettoken'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Note')),
                ('comment', models.TextField(verbose_name='Commentaire')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='account.customerprofile', verbose_name='Client')),
                ('firm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='account.firmprofile', verbose_name='Entreprise')),
            ],
            options={
                'verbose_name': 'Avis',
                'ordering': ['-created_at'],
                'unique_together': {('firm', 'customer')},
            },
        ),
    ]
