# Generated by Django 5.2.4 on 2025-07-26 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_passwordresettoken'),
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='review',
            options={'ordering': ['-created_at'], 'verbose_name': 'Avi'},
        ),
        migrations.AddIndex(
            model_name='review',
            index=models.Index(fields=['firm'], name='firm_idx'),
        ),
        migrations.AddIndex(
            model_name='review',
            index=models.Index(fields=['-created_at'], name='date_desc_idx'),
        ),
    ]
