# Generated by Django 5.2.4 on 2025-07-26 13:41

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_passwordresettoken'),
        ('reviews', '0002_alter_review_options_review_firm_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReviewResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('response_text', models.TextField(verbose_name="Réponse de l'entreprise")),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='review',
            options={},
        ),
        migrations.RemoveIndex(
            model_name='review',
            name='firm_idx',
        ),
        migrations.RemoveIndex(
            model_name='review',
            name='date_desc_idx',
        ),
        migrations.AlterUniqueTogether(
            name='review',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='reviewresponse',
            name='firm',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.firmprofile', verbose_name='Entreprise répondante'),
        ),
        migrations.AddField(
            model_name='reviewresponse',
            name='review',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='response', to='reviews.review', verbose_name='Avis concerné'),
        ),
    ]
