# Generated by Django 5.2.4 on 2025-07-27 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_passwordresettoken'),
        ('reviews', '0003_reviewresponse_alter_review_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='review',
            options={'ordering': ['-created_at'], 'verbose_name': 'Avi'},
        ),
        migrations.AlterModelOptions(
            name='reviewresponse',
            options={'ordering': ['-created_at'], 'verbose_name': 'Réponse à un avis'},
        ),
        migrations.AlterUniqueTogether(
            name='review',
            unique_together={('firm', 'customer')},
        ),
        migrations.AddIndex(
            model_name='review',
            index=models.Index(fields=['firm'], name='firm_idx'),
        ),
        migrations.AddIndex(
            model_name='review',
            index=models.Index(fields=['-created_at'], name='date_desc_idx'),
        ),
    ]
