# Generated by Django 5.2.4 on 2025-08-25 19:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0004_alter_review_options_alter_reviewresponse_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='review',
            options={'ordering': ['-created_at'], 'verbose_name': 'Avi', 'verbose_name_plural': 'Avis'},
        ),
        migrations.AlterModelOptions(
            name='reviewresponse',
            options={'ordering': ['-created_at'], 'verbose_name': 'Réponse à un avis', 'verbose_name_plural': 'Réponses aux avis'},
        ),
        migrations.AddField(
            model_name='review',
            name='useful_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Nombre de votes utiles'),
        ),
        migrations.CreateModel(
            name='UsefulVote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('review', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='useful_votes', to='reviews.review', verbose_name='Avis')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
            ],
            options={
                'verbose_name': 'Vote utile',
                'verbose_name_plural': 'Votes utiles',
            },
        ),
        migrations.AddField(
            model_name='review',
            name='users_who_found_useful',
            field=models.ManyToManyField(blank=True, related_name='useful_reviews', through='reviews.UsefulVote', to=settings.AUTH_USER_MODEL, verbose_name="Utilisateurs ayant trouvé l'avis utile"),
        ),
        migrations.AddIndex(
            model_name='usefulvote',
            index=models.Index(fields=['user', 'review'], name='user_review_vote_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='usefulvote',
            unique_together={('user', 'review')},
        ),
    ]
