# Generated by Django 5.2.3 on 2025-07-14 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_customerprofile_firmprofile_delete_my_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='firmprofile',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
    ]
