# Generated by Django 5.2.4 on 2025-08-03 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_passwordresettoken'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='firmprofile',
            name='siret',
        ),
        migrations.AddField(
            model_name='firmprofile',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Numéro de téléphone'),
        ),
    ]
