# Generated by Django 5.1.7 on 2025-08-24 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_remove_firmprofile_siret_firmprofile_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerprofile',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pictures/customers/', verbose_name='Photo de profil'),
        ),
        migrations.AddField(
            model_name='firmprofile',
            name='company_logo',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pictures/firms/', verbose_name="Logo de l'entreprise"),
        ),
    ]
