GET http://localhost:8000/account/customer/profile/ 
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzU1NTQ5MTUxLCJpYXQiOjE3NTU1NDE5NTIsImp0aSI6Ijc0ZWJjOGU0YjZjMTQ2YWE5NjU1MmJiODdhNDZiY2UwIiwidXNlcl9pZCI6IjEwIn0.3jFxZHLVdNTcX24uM_OX3uLJYJZunR26ub6Ok8OBp44

### Get information about firm profile 
GET http://localhost:8000/account/firm/profile/ 
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzU2NDMzODM4LCJpYXQiOjE3NTYzNDc0MzksImp0aSI6ImE1ZTFmZjU0MDhkNjQ0YzZiNGNhNGFkNjQ2N2UyZjJkIiwidXNlcl9pZCI6IjE5In0.ZXxGOUj3RSHoa45uYKaNei4aFAxeJs_NqbYR2VdiXF4

### Edit information about firm profile 
PUT http://localhost:8000/account/firm/profile/ 
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzU1NjA5MDk1LCJpYXQiOjE3NTU2MDE4OTUsImp0aSI6IjcyOGNjZWUyMDA5ZDQ3ZTFiMmZiMjM2ZjZmOWRhNzZlIiwidXNlcl9pZCI6MTN9.Icj8M9hRW9jbCQPgIhrVPvpo_kD29C9LFb0lDT45NZM

{
  "address": "Adjame paillet, rue de l'aménagement"
}

### Get informations with credentials
POST http://127.0.0.1:8000/account/login/
Content-Type: application/json

{
  "email": "marie.martin@email.com",
  "password": "securepassword123"
}

{
  "refresh": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoicmVmcmVzaCIsImV4cCI6MTc1NjE1NjY1NSwiaWF0IjoxNzU1OTgzODU1LCJqdGkiOiI5NTIzMjY4ODllNGY0ZTQ1ODg1NmIyMWU2NjEyZThjNyIsInVzZXJfaWQiOjh9.i5nvmBJfgvysOVOPqdxJ54DYd-wVoQ0IAV13N93xViU",
  "access": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzU1OTkxMDU1LCJpYXQiOjE3NTU5ODM4NTUsImp0aSI6IjIxNzE1ZDQzYWEzNjRkZTFiZDJjMjhkYTNjNDFhMGQyIiwidXNlcl9pZCI6OH0.B31uU5f7qrmRGtJNgYvIrEx4ap-8LcPr1nLOMMYq3o0",
  "username": "marie.martin"
}

###
POST http://127.0.0.1:8000/account/token/refresh/
Content-Type: application/json

{
  "refresh": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoicmVmcmVzaCIsImV4cCI6MTc1NTY3ODA3MCwiaWF0IjoxNzU1NTkxNjcwLCJqdGkiOiI0MGExZGUwZjQwNzg0OTZkYTE5ZWFlOTkxNjI0ODllOSIsInVzZXJfaWQiOjEzfQ.Tx1bM194yYnJbprZoQdgKz5-yrAYnip6e7b9Cejz1xU"
}