# Generated by Django 5.2.4 on 2025-07-30 00:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0005_passwordresettoken'),
    ]

    operations = [
        migrations.CreateModel(
            name='Companies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('RH', 'RESTAURATION ET HOTELLERIES'), ('CE', 'COMMERCE ET ECOMMERCE'), ('TL', 'TRANSPORT ET LOGISTIQUE'), ('SB', 'SANTE ET BIEN-ETRE'), ('FB', 'FINANCE ET BANQUE'), ('TC', 'TELECOMMUNICATION'), ('EF', 'EDUCATION ET FORMATION'), ('AS', 'ARTISANAT ET SERVICES LOCAUX'), ('LD', 'LOISIR ET DIVERTISSEMENT'), ('SP', 'SERVICES PUBLICS'), ('AG', 'AGROINDUSTRIE'), ('A', 'AUTRE')], max_length=3)),
                ('web_site', models.CharField(blank=True, max_length=100)),
                ('firm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.firmprofile')),
            ],
        ),
    ]
