# Generated by Django 5.2.3 on 2025-07-12 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('CM', 'Commerce'), ('AL', 'Alimentation'), ('IM', 'Immobilier')], max_length=2)),
            ],
        ),
    ]
