# Generated by Django 5.1.7 on 2025-08-03 21:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0006_remove_firmprofile_siret_firmprofile_phone_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('RH', 'Restauration & Hôtellerie'), ('CE', 'Commerce & E-commerce'), ('TL', 'Transport & Logistique'), ('SB', 'Santé & Bien-être'), ('FB', 'Services Financiers & Banques'), ('TC', 'Télécommunications'), ('EF', 'Éducation & Formation'), ('AS', 'Artisanat & Services Locaux'), ('IM', 'Immobilier'), ('LD', 'Loisirs & Divertissement'), ('SP', 'Services Publics & Administration'), ('AI', 'Agriculture & Agro-industrie'), ('OT', 'Autre')], default='OT', max_length=2, verbose_name='Catégorie')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('website', models.URLField(blank=True, null=True, verbose_name='Site Web')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de mise à jour')),
                ('name', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='account.firmprofile')),
            ],
            options={
                'verbose_name': 'Entreprise',
                'verbose_name_plural': 'Entreprises',
                'ordering': ['name'],
            },
        ),
    ]
