# Generated by Django 5.2.4 on 2025-07-30 00:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name="Nom de l'entreprise")),
                ('category', models.CharField(choices=[('RH', 'Restauration & Hôtellerie'), ('CE', 'Commerce & E-commerce'), ('TL', 'Transport & Logistique'), ('SB', 'Santé & Bien-être'), ('FB', 'Services Financiers & Banques'), ('TC', 'Télécommunications'), ('EF', 'Éducation & Formation'), ('AS', 'Artisanat & Services Locaux'), ('IM', 'Immobilier'), ('LD', 'Loisirs & Divertissement'), ('SP', 'Services Publics & Administration'), ('AI', 'Agriculture & Agro-industrie'), ('OT', 'Autre')], default='OT', max_length=2, verbose_name='Catégorie')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('website', models.URLField(blank=True, null=True, verbose_name='Site Web')),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True, verbose_name='Numéro de téléphone')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de mise à jour')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_companies', to=settings.AUTH_USER_MODEL, verbose_name='Créé par')),
            ],
            options={
                'verbose_name': 'Entreprise',
                'verbose_name_plural': 'Entreprises',
                'ordering': ['name'],
            },
        ),
        migrations.DeleteModel(
            name='Companies',
        ),
    ]
