# Generated by Django 5.1.7 on 2025-08-24 18:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='document_1',
            field=models.FileField(blank=True, help_text='Téléchargez un document PDF (max. 10MB)', max_length=500, null=True, upload_to='company_documents/%Y/%m/%d/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])], verbose_name='Document administratif 1'),
        ),
        migrations.AddField(
            model_name='company',
            name='document_2',
            field=models.FileField(blank=True, help_text='Téléchargez un document PDF (max. 10MB)', max_length=500, null=True, upload_to='company_documents/%Y/%m/%d/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])], verbose_name='Document administratif 2'),
        ),
        migrations.AddField(
            model_name='company',
            name='documents_verified',
            field=models.BooleanField(default=False, help_text="Indique si les documents administratifs ont été vérifiés par l'administration", verbose_name='Documents vérifiés'),
        ),
    ]
