# Generated by Django 5.2.3 on 2025-07-12 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='category',
            field=models.CharField(choices=[('Commerce', 'Commerce'), ('Alimentation', 'Alimentation'), ('Immobilier', 'Immobilier')], max_length=100),
        ),
    ]
