# Generated by Django 5.2.4 on 2025-07-30 00:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_passwordresettoken'),
        ('companies', '0002_company_delete_companies'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_companies', to='account.firmprofile', verbose_name='Créé par'),
        ),
        migrations.AlterField(
            model_name='company',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.firmprofile'),
        ),
    ]
