# Generated by Django 5.1.7 on 2025-07-31 12:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_passwordresettoken'),
        ('companies', '0002_company_delete_companies'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='created_by',
        ),
        migrations.AlterField(
            model_name='company',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.firmprofile'),
        ),
    ]
