# Generated by Django 5.2.4 on 2025-07-30 00:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0003_alter_company_created_by_alter_company_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='created_by',
        ),
    ]
